replicaCount: 1

image:
  repository: ghcr.io/{CHANGE_ME}/octopus-workshop-instruqt-argo/sample.frontend
  tag: 25.1.3
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull-secret

service:
  type: ClusterIP
  port: 81
